services:
  - type: web
    name: adaptfit-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
